### ISSUE TITLE
Separate the U.S. model example from core energyPATHWAYS

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#31]
As this project closes in on an initial fully functional version of the model, it would be worth pealing the U.S. model example away from the core EnergyPATHWAYS package. The advantages are:
1. The structure and relationship between core model and model use is easier to understand for new users
2. The structure change will help facilitate the creation of small model examples for training purposes
3. Once the project is registered on [PyPi](https://pypi.python.org/pypi) the we can install the core model using any package manager and it will be beneficial to have this separate from any single instance of the model.

**Comment by mactyr** [comment]
>  it will be beneficial to have this separate from any single instance of the model.

Well, I do think it can be helpful to include example usage code with a package (especially a complicated one like this). I agree that we probably don't need the full U.S. model there in the long run, but keeping some simpler examples in the main repo may be a good idea.

**Comment by ryandrewjones** [comment]
One thing to consider is that site packages are in a separate folder buried in the python directory, which you don't want to work from directly or mess with directly. When you use a package manager like PIP, that is where it will put core energyPATHWAYS (along with all of the examples you refer to). I'm not against having them both places, perhaps, but to me it seems simpler to have a separate repository with a number of examples and then a README that links the two.

**Comment by ryandrewjones** [comment]
To put that more explicitly, if someone uses pip install,we don't want them to chase the package into the Anaconda environment to grab and work with the examples.

**Comment by mactyr** [comment]
That's a reasonable concern, but I think we can address it and get the best of both worlds.

First, the case for including the basic examples in the module is that it avoids a whole class of versioning synchronization issues, where someone installs the package, gets distracted, then comes back a month later and downloads an example only to find that it doesn't work right because there have been changes to the system. (Eventually this will be less of an issue because pathways will mature, but I think we've got a ways to go until 1.0.) Relatedly, I think keeping them in the same repo will help remind us that we need to keep them updated when there's a related code change, and not think of them as something external. Finally, we could potentially leverage some simpler ones as integration tests, which would also belong in the same repo.

To address your concern: eventually we will need a cleaner, more consistent way to do a standard model run than asking people to hack on the example main.py. I'm imagining something like:

`python -m energyPATHWAYS run my_model`

Once we have that wired up, it should be easy to do something like have the command search the examples/ directory for the requested model if it's not found in the current directory.

This is a slight simplification that assumes that the models are in a document format, or perhaps a sqlite db. If they're in a dump that needs to be loaded into a database first then we could have some kind of helper like `python -m energyPATHWAYS load dump_file.sql`, which could search the example path as a fallback. That would run a `pg_restore` and then you could do `python -m energyPATHWAYS run db_name`.

There are a bunch of possible variations on this theme; I'm not saying that these exact commands are the best, just saying that we can provide some commands that ought to make it simple to run included examples without needing to reach into the examples folder directly. (And if we want users to be able to easily find the examples to review their content, we can provide a `python -m energyPATHWAYS help` that tells them exactly where it is so they don't have to go digging... although they could just as easily _view_ them on the github site!)

**Comment by ryandrewjones** [comment]
I'm in agreement about ideal ways to eventually run the model, though I'm not sure how this helps with the fact that all of the database data would be located inside of the package manager. And, for a user trying to see what they were running, they would have to go find it.

Regardless, this is something on the back burner. I don't think the splitting between core model and model instances solves anything before v1.0.

My main observation right now is just that eventually it will be helpful to split the U.S. model from the core model (the U.S. model is large, takes a long time to run, and is a difficult first example for a user). Whether we have toy cases packaged with the core model is a separate discussion and doing so does have advantages as you and Sam have identified.

**Comment by sborgeson** [comment]
I think I can summarize what I see as good practice this way: you want the module to come with a set of tests that exercise the code, check for platform dependencies (like optimizer run times and differences?), and whose implementation is a good resource for people working to understand your code better. Concretely, you can enable test support in setup.py (i.e. python setup.py test) like this:
https://python-packaging.readthedocs.org/en/latest/testing.html

And you can package any test related data, etc., as non-code files in your package:
https://python-packaging.readthedocs.org/en/latest/non-code-files.html

I think it makes sense to put these mechanisms in place for v1.0, even if they aren't fully utilized. On the other hand, I'm not sure I would call something 1.0 until a testing framework is in place. What's the rush to call it 1.0?

**Comment by ryandrewjones** [comment]
Sam I'm in agreement, thanks for the resources. And no rush here to call anything v1.0, that's just been our shorthand for a model that supports backwards compatibility, which is still a long time away.
