### ISSUE TITLE
Use of pandas.drop() function giving unexpected behavior

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#52]
This is connected to a known ticket in pandas: https://github.com/pydata/pandas/issues/2770

We were using pandas.drop in two places in the model. One in TimeSeries.clean() the other in util.remove_df_elements(data, elements, level).

In both cases, the use of drop wasn't fully "removing" the index that we wanted, only dropping the data, so that if df.index was called, the original index was still there. This in turn caused a bug while doing a merge in the util.DfOper class before multiplying two MultiIndex dataframes together.

We are getting around this issue by using pandas.reindex instead of pandas.drop.

**Comment by ryandrewjones** [comment]
This has been fixed in commit 3977063e121af51585612412afa57992d83a283d and 1cb39c76b1da961ccd38cdc83566c18028cad02f

**Comment by mactyr** [comment]
I'm really excited to see that you wrote some tests around this fix, that's awesome!

If I might make one more suggestion: it would be excellent to leave a comment in the code above the lines that changed from .drop() to .reindex() with a brief mention that it's important to use reindex rather than drop (can even include the url of this ticket), so when someone comes across it in the future and thinks, "seems like 'drop()' would be a lot more succinct here", they're warned against it. "Someone" could be an outside developer or you a year from now. 😉
