### ISSUE TITLE
Linking embodied emissions to direct emissions rather than embodied carbon

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#6]
**Steps to reproduce**
Calculate embodied carbon for any demand sector that uses a supply node that sequesters carbon

**Observed behavior**
Embodied emissions are a function of the physical amount of carbon upstream

**Desired behavior**
Embodied emissions should be calculated based on direct emissions so that if a stream of carbon is sequestered, it does not show up in embodied calculations. To do this, we should calculate direct emissions first and then multiply by the inverse of the input-output table.

**Comment by mactyr** [comment]
I suggest using the `bug` label (tag) rather than putting "bug" in the title (I've just taken the liberty of adding the label and changing the title). The label is easier to search/filter on and see at a glance.

We can also easily create custom labels for any ticket classification that's important to us.

**Comment by BenEvolved** [comment]
Model now calculates emissions appropriately based on emissions within supply nodes or demand subsectors. As an example,  embodied supply emissions would be calculated not for the natural gas supply node, but from the CCGT node where that natural gas is combusted. All emissions results are reported in the output .csv file 'emissions' located in the model 'outputs' folder.
