### ISSUE TITLE
Negative values observed in the stock rollover

### ISSUE THREAD

**Issue by ryandrewjones** [energyPATHWAYS/energyPATHWAYS#7]
**Steps to reproduce**
Attempting to run the model through 2050 - Error encountered [in] "node 8 in elements (68,) year 2019"

**Observed behavior**
Model raises an exception stating that negative stock values are encountered in the stock rollover

**Desired behavior**
Negative stock values should never be observed, thus the origin of the negative values should be found and fixed.

**Comment by mactyr** [comment]
Adding `bug` label and removing bug from the title, as with #6.

**Comment by ryandrewjones** [comment]
This was caused by an extremely large stock that was causing round errors. The rounding error was caused by the following math:

> > >  1.0 - 1e-17
> > > 1.0

No true fix was available here (or needed) because the stock was on the order of 10e+23 and was itself the product of another bug. However, in the step that was causing the negative value, a clip function was inserted to ensure no negative values make it into the stock, nevertheless.

**Comment by mactyr** [comment]
Glad this is sorted out! It's a good idea to note somewhere in the ticket the commit(s) in which related changes were made. If you put "#7" in your commit message somewhere github will link them automatically, otherwise I'd suggest putting the commit id in a comment and github will make it a link automatically (you actually only need the first seven or so characters from the id for that to work).

**Comment by ryandrewjones** [comment]
Bug fixed in commit 636a496
